/*******************************************************************************
 * *  Copyright (C) 2021 LINKS Foundation
 * 
 * This file is based on the ROSOSGi open-source project which is a part of DIANNE  -  Framework for distributed artificial neural networks
 * 
 * DIANNE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package actionlib;

public interface TestRequestGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "actionlib/TestRequestGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nint32 TERMINATE_SUCCESS = 0\nint32 TERMINATE_ABORTED = 1\nint32 TERMINATE_REJECTED = 2\nint32 TERMINATE_LOSE = 3\nint32 TERMINATE_DROP = 4\nint32 TERMINATE_EXCEPTION = 5\nint32 terminate_status\nbool ignore_cancel  # If true, ignores requests to cancel\nstring result_text\nint32 the_result    # Desired value for the_result in the Result\nbool is_simple_client\nduration delay_accept  # Delays accepting the goal by this amount of time\nduration delay_terminate  # Delays terminating for this amount of time\nduration pause_status  # Pauses the status messages for this amount of time\n";
  static final int TERMINATE_SUCCESS = 0;
  static final int TERMINATE_ABORTED = 1;
  static final int TERMINATE_REJECTED = 2;
  static final int TERMINATE_LOSE = 3;
  static final int TERMINATE_DROP = 4;
  static final int TERMINATE_EXCEPTION = 5;
  int getTerminateStatus();
  void setTerminateStatus(int value);
  boolean getIgnoreCancel();
  void setIgnoreCancel(boolean value);
  java.lang.String getResultText();
  void setResultText(java.lang.String value);
  int getTheResult();
  void setTheResult(int value);
  boolean getIsSimpleClient();
  void setIsSimpleClient(boolean value);
  org.ros.message.Duration getDelayAccept();
  void setDelayAccept(org.ros.message.Duration value);
  org.ros.message.Duration getDelayTerminate();
  void setDelayTerminate(org.ros.message.Duration value);
  org.ros.message.Duration getPauseStatus();
  void setPauseStatus(org.ros.message.Duration value);
}
