
language: java

# travis use default openjdk8, it doesn't support oraclejdk8, but the oraclejdk11 
jdk:
  - openjdk8

#script: ./gradlew --continue

env:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "'-s .m2/settings.xml -B'"
  MAVEN_DEPLOY_OPTS: "'-DaltReleaseDeploymentRepository=brain-iot-releases::default::https://nexus.repository-pert.ismb.it/repository/maven-releases -DaltSnapshotDeploymentRepository=brain-iot-snapshots::default::https://nexus.repository-pert.ismb.it/repository/maven-snapshots'"
#  CI_DEBUG_TRACE: "true"

# Cache downloaded dependencies and plugins between builds.
cache:
  directories:
    - .m2/repository

install:
    - wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip
    - unzip -qq apache-maven-3.6.3-bin.zip
    - export M2_HOME=$PWD/apache-maven-3.6.3
    - export PATH=$M2_HOME/bin:$PATH

script:
    - ./gradlew clean build install


after_success:
    - ./gradlew resolve

deploy:
  provider: script
  script: ./gradlew uploadArchives && ./build.sh
  skip_cleanup: true
  on:
    branch: smartbehavior

#  script: ./gradlew build uploadArchives && ./build.sh

#end

