sudo: false

language: java

jdk:
  - oraclejdk11

#script: ./gradlew --continue

env:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "'-s .m2/settings.xml -B'"
  MAVEN_DEPLOY_OPTS: "'-DaltReleaseDeploymentRepository=brain-iot-releases::default::https://nexus.repository-pert.ismb.it/repository/maven-releases -DaltSnapshotDeploymentRepository=brain-iot-snapshots::default::https://nexus.repository-pert.ismb.it/repository/maven-snapshots'"
#  CI_DEBUG_TRACE: "true"

# Cache downloaded dependencies and plugins between builds.
cache:
  directories:
    - $HOME/.m2/repository



install:
    - ./gradlew --version
    - ./gradlew clean build

script:
    - ./gradlew resolve export 


after_success:
     - ./gradlew uploadArchives


#end
