/*******************************************************************************
 * *  Copyright (C) 2021 LINKS Foundation
 * 
 * This file is based on the ROSOSGi open-source project which is a part of DIANNE  -  Framework for distributed artificial neural networks
 * 
 * DIANNE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package twist_mux_msgs;

public interface JoyTurboAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "twist_mux_msgs/JoyTurboAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nJoyTurboActionGoal action_goal\nJoyTurboActionResult action_result\nJoyTurboActionFeedback action_feedback\n";
  twist_mux_msgs.JoyTurboActionGoal getActionGoal();
  void setActionGoal(twist_mux_msgs.JoyTurboActionGoal value);
  twist_mux_msgs.JoyTurboActionResult getActionResult();
  void setActionResult(twist_mux_msgs.JoyTurboActionResult value);
  twist_mux_msgs.JoyTurboActionFeedback getActionFeedback();
  void setActionFeedback(twist_mux_msgs.JoyTurboActionFeedback value);
}
