/*******************************************************************************
 * *  Copyright (C) 2021 LINKS Foundation
 * 
 * This file is based on the ROSOSGi open-source project which is a part of DIANNE  -  Framework for distributed artificial neural networks
 * 
 * DIANNE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package control_msgs;

public interface GripperCommandAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "control_msgs/GripperCommandAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nGripperCommandActionGoal action_goal\nGripperCommandActionResult action_result\nGripperCommandActionFeedback action_feedback\n";
  control_msgs.GripperCommandActionGoal getActionGoal();
  void setActionGoal(control_msgs.GripperCommandActionGoal value);
  control_msgs.GripperCommandActionResult getActionResult();
  void setActionResult(control_msgs.GripperCommandActionResult value);
  control_msgs.GripperCommandActionFeedback getActionFeedback();
  void setActionFeedback(control_msgs.GripperCommandActionFeedback value);
}
