/*******************************************************************************
 * *  Copyright (C) 2021 LINKS Foundation
 * 
 * This file is based on the ROSOSGi open-source project which is a part of DIANNE  -  Framework for distributed artificial neural networks
 * 
 * DIANNE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package control_msgs;

public interface PointHeadGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "control_msgs/PointHeadGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\ngeometry_msgs/PointStamped target\ngeometry_msgs/Vector3 pointing_axis\nstring pointing_frame\nduration min_duration\nfloat64 max_velocity\n";
  geometry_msgs.PointStamped getTarget();
  void setTarget(geometry_msgs.PointStamped value);
  geometry_msgs.Vector3 getPointingAxis();
  void setPointingAxis(geometry_msgs.Vector3 value);
  java.lang.String getPointingFrame();
  void setPointingFrame(java.lang.String value);
  org.ros.message.Duration getMinDuration();
  void setMinDuration(org.ros.message.Duration value);
  double getMaxVelocity();
  void setMaxVelocity(double value);
}
