/*******************************************************************************
 * *  Copyright (C) 2021 LINKS Foundation
 * 
 * This file is based on the ROSOSGi open-source project which is a part of DIANNE  -  Framework for distributed artificial neural networks
 * 
 * DIANNE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package tf2_msgs;

public interface LookupTransformGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "tf2_msgs/LookupTransformGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#Simple API\nstring target_frame\nstring source_frame\ntime source_time\nduration timeout\n\n#Advanced API\ntime target_time\nstring fixed_frame\n\n#Whether or not to use the advanced API\nbool advanced\n\n";
  java.lang.String getTargetFrame();
  void setTargetFrame(java.lang.String value);
  java.lang.String getSourceFrame();
  void setSourceFrame(java.lang.String value);
  org.ros.message.Time getSourceTime();
  void setSourceTime(org.ros.message.Time value);
  org.ros.message.Duration getTimeout();
  void setTimeout(org.ros.message.Duration value);
  org.ros.message.Time getTargetTime();
  void setTargetTime(org.ros.message.Time value);
  java.lang.String getFixedFrame();
  void setFixedFrame(java.lang.String value);
  boolean getAdvanced();
  void setAdvanced(boolean value);
}
