/*******************************************************************************
 * *  Copyright (C) 2021 LINKS Foundation
 * 
 * This file is based on the ROSOSGi open-source project which is a part of DIANNE  -  Framework for distributed artificial neural networks
 * 
 * DIANNE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package tf2_msgs;

public interface LookupTransformAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "tf2_msgs/LookupTransformAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nLookupTransformActionGoal action_goal\nLookupTransformActionResult action_result\nLookupTransformActionFeedback action_feedback\n";
  tf2_msgs.LookupTransformActionGoal getActionGoal();
  void setActionGoal(tf2_msgs.LookupTransformActionGoal value);
  tf2_msgs.LookupTransformActionResult getActionResult();
  void setActionResult(tf2_msgs.LookupTransformActionResult value);
  tf2_msgs.LookupTransformActionFeedback getActionFeedback();
  void setActionFeedback(tf2_msgs.LookupTransformActionFeedback value);
}
